### ISSUE TITLE
Name in profile view is not aligned to the left

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/Reaxit#103]
### Describe the bug
The name of the profile you're visiting comes down on top of the user profile image. But it is aligned really weird. Not centered, more like half-way.

### How to reproduce
1. Go to a member profile
2. Scroll down and up
3. Note the member's name

### Expected behaviour
Should be properly aligned to the left

### Screenshots
Don't really want to add all that here. :p

### Environment:
 - Device: Oneplus 8T
 - OS: Android 11
 - Version: a3d22e0ea377b4e2b5ca7818d195333c186f1372

**Comment by se-bastiaan** [comment]
Now it's centered?

**Comment by DeD1rk** [comment]
Yes, I pushed some stuff

**Comment by DeD1rk** [comment]
Oh you mean it shouldnt be centered? It has to be to the right of the back button though, so actually it was already left-aligned

**Comment by DeD1rk** [comment]
I just checked on the old app on android, I'll try to see if i can get it to work like it does there. Hadn't ever seen that oops.
