### ISSUE TITLE
Menu / Settings styling 

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/Reaxit#134]
### Describe the bug
- There is an about button in the menu that has different styling from other menu items, unclear why exactly. The information behind this button just belongs in settings in it's own section.
- There is different vertical spacing of the UI elements in the menu header and the menu items themselves.
- The items are titles and could use the Oswald font because of that, moreover the icons in the items have different spacing on the left and right.
- In the settings there is a title for the notifications but not above the theme part of the settings.
- The theme settings have an icons, the notifications don't have icons for some reason making this inconsistent.
- The title font Oswald is used for the theme selected value.
- There are 5 different types of fonts. This should be split in a title, subtitle, subsubtitle and regular text.
- It would be better if the vertical padding of all parts if more than the horizontal padding. Preferably doubled so that we're not trying to put everything in 1cm2. In general everything could use a bit more space.

### How to reproduce
1. Go to the menu and the settings view

**Comment by se-bastiaan** [comment]
Extra note:
- Selecting a menu item using an animation to open a view on top, while it should change the view behind the menu and close the menu

**Comment by DeD1rk** [comment]
> * Selecting a menu item using an animation to open a view on top, while it should change the view behind the menu and close the menu

This seems correct, but is very poorly supported by the framework. The way to solve it would be to have a single widget that plays the role of each top-level page. At the Technicie live thing we all really don't care about the difference, or at least it has a very low priority (not needed for first release), so if we really want to change this it should be in a new issue. I'll create that, though we might end up just closing it.
