### ISSUE TITLE
Change top-level page transition to happen below drawer?

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/Reaxit#147]
This requires us to have a single page widget that wraps each possible top-level screen. See also #134.

**Comment by se-bastiaan** [comment]
> This seems correct, but is very poorly supported by the framework. The way to solve it would be to have a single widget that plays the role of each top-level page. At the Technicie live thing we all really don't care about the difference, or at least it has a very low priority (not needed for first release), so if we really want to change this it should be in a new issue. I'll create that, though we might end up just closing it.

Navigation transitions are important to understand the structure of the application. All the items in the navigation are on the same level so they should not open as if they are added on top. I recommend you to read more about these patterns here: https://material.io/design/navigation/navigation-transitions.html

There are [some good examplles](https://github.com/TechieBlossom/sidebar_animation_flutter/blob/master/lib/bloc.navigation_bloc/navigation_bloc.dart) on how to do this as well.

And it may not be necessary to have a working app. But you're rebuilding an application that was carefully crafted to apply all these design elements correctly. At least show some interest in matching that work.

**Comment by DeD1rk** [comment]
> There are some good examplles on how to do this as well.

That's indeed quite a nice example. It sadly does not support having a scaffold as content (since a single scaffold is used to surround the content). That means that we'd need to make a wrapper that manages the drawer, which a scaffold would normally do. It's feasible, but quite a large change. And since we find it not disturbing, I think releasing has a higher priority. 

An alternative that is not ideal, but may be better and quite trivial (also keeps the code side of navigation simple), would be to change the transition animation of the top-level pages. Then instead of the slide-over animation we can have fade-through to emphasise the horizontal relation. The animation then still takes place on top of the drawer (drawer fades out with the old screen, new screen without drawer fades in), but there's not the slide-over. That does not require large changes to routing at all.

**Comment by se-bastiaan** [comment]
> An alternative that is not ideal, but may be better and quite trivial (also keeps the code side of navigation simple), would be to change the transition animation of the top-level pages. Then instead of the slide-over animation we can have fade-through to emphasise the horizontal relation. The animation then still takes place on top of the drawer (drawer fades out with the old screen, new screen without drawer fades in), but there's not the slide-over. That does not require large changes to routing at all.

I think this is a good idea to at least try. It sounds like it makes more sense since nothing is 'stacked' on top.
