### ISSUE TITLE
Show day of week in EventScreen

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/Reaxit#165]
Seeing only the date and time of an event is often impractical, because no-one knows what day a date is. So I suggest we also display the weekday in the event detail screen. 

This takes up some more space, so in the current layout the event time fields may start taking up two lines. Some options are `Monday 20 Sep 2021, 13:37', 'Mon 20 Sep 2021, 13:37', 'Monday 20-09-2021, 13:37', 'Monday 13:37, <date>', '13:37, Monday <date>', or any other format. There may be some option that is nice and fits on a single line, or an order that looks nice even when split over 2 lines.

**Comment by Jorritboer** [comment]
Thanks for the easy and fun issue, please don't take it away from me this time

**Comment by DeD1rk** [comment]
Hahaha sorry, I promise I won't steal this one!
