### ISSUE TITLE
Queued registrations show up in admin.

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/Reaxit#166]
### Describe the bug
Similarly to #162, registrations for events that are in queue are not filtered out. That is confusing, so we should fix it. Probably it's best to just filter them out. It might also be an option to clearly indicate queued registrations as such, instead of not showing them at all.

**Comment by DeD1rk** [comment]
The concrexit part [concrexit/#2071](https://github.com/svthalia/concrexit/issues/2071) is more complicated than I'd hoped, so perhaps it's a good idea to use client-side filtering for now, and leave this issue open to replace it when concrexit supports it.

**Comment by Jorritboer** [comment]
I will indeed just fix this client side for now. Later it would also be nice to show cancellations and waitinglist. I'll make an issue for that later and would be happy to take that on then too
