### ISSUE TITLE
Filters and ordering in admins

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/Reaxit#168]
It might be convenient for event organiser to have filters in the event and food admins, for example on unpaid/paid, not present, and perhaps some other filters.

**Comment by JAicewizard** [comment]
Is there any reason to sort on anything? For most of the fields you can sort on it doesn't really make any sense. Maybe we can cluster the food orders by what was ordered? But much more seems useless.

**Comment by DeD1rk** [comment]
Ordering on product seems useful yes. Also ordering on 'paid' 'present' etc. can be nice to get a bit of an overview and making it easy to find the relevant people, without moving the other items out of view.
