### ISSUE TITLE
Event search view shows old events first

### ISSUE THREAD

**Issue by KiOui** [svthalia/Reaxit#175]
### Describe the bug
The search view for events shows old events first

![image](https://user-images.githubusercontent.com/38525109/145864196-aec73cc7-51fb-43d4-8d74-90a923bc9425.png)

### How to reproduce
1. Go to the Calendar
2. Search for an event (e.g. Weekend)

### Expected behaviour
Show new events first.

**Comment by DeD1rk** [comment]
This was intentional, but I guess it doesn't make sense indeed 😆

**Comment by DeD1rk** [comment]
Although actually, having it reversed is also strange

**Comment by DeD1rk** [comment]
As proposed by @JAicewizard in #309, let's have it visually in the same order, but lazy load upwards (towards older events). Note that in the cubit everything will need to be reversed: fetching ordered by end time decreasing I think.

**Comment by JAicewizard** [comment]
Current idea: search view is the same as normal view, you scroll down to expand downwards, scrolling up does the pull to refresh thing, and a "load more" button at the top to go upwards. Easy to implement, and also allows going back in time in the normal calendar & refreshing the search. Only downside is going back in time is not very nice, but if you know what kind of event you are looking for you can do a more specific search, if you aren't searching its still an upgrade over not being able to do so.

**Comment by DeD1rk** [comment]
I probbly misunderstood but O don't think that will work, because the api doesn't really support loading 'middle' pages

**Comment by JAicewizard** [comment]
You can use
```
api.getEvents(
        end: start,
        search: query,
        ordering: '-end',
        limit: pageSize,
        offset: _nextPastOffset,
      );
```
to get the last `_nextPastOffset` events before `start` (with offset `pageSize`) just like you can with loading future pages. I played around a bit with it on the website and that seemed to work, havnt tried in the app itself yet
