### ISSUE TITLE
Push-notification redirects to website instead of app

### ISSUE THREAD

**Issue by TippieCodes** [svthalia/Reaxit#177]
### Describe the bug
Clicking on a 'registrations for 'EVENT' starts in 1 hour redirects to the website rather than the app.

### How to reproduce
1. Click on a received registrations start in 1 hour push notification.
2. Observe where you are redirected.

### Expected behaviour
The app should open the event page for the respective event.

### Screenshots
N/A

### Environment:
 - Device: Iphone X
 - OS: iOS 15.2
 - Version 3.0.0

### Additional context
N/A

**Comment by DeD1rk** [comment]
Basically we need to somehow check whether the app ia able to handle the url in a push notification, and if it is, forward it to the routing system. Communicating navigation down into the framework may be tricky, but I've seen some package doing it.

**Comment by DeD1rk** [comment]
Closed by #157.
