### ISSUE TITLE
Visiting registrations causes "An unknown error occured."

### ISSUE THREAD

**Issue by TippieCodes** [svthalia/Reaxit#182]
### Describe the bug
When you try to view the registrations by clicking on the wheel of an event you / your committee hosted it shows a sad cloud with "An unknown error occurred."

### How to reproduce
1. Go to any event you have permission to view the registrations for
2. Click on the event to open it
3. Click on the wheel in the top right to view the registrations
4. Observe the sad cloud that says "An unknown error occurred."

### Expected behaviour
It should show the registrations and allow the user to manage them, see who has paid etc.

### Screenshots
[video
](https://imgur.com/a/kqN20uM)
### Environment:
 - Device: iPhone X
 - OS: iOS 15.2
 - Version: 3.0.0

### Additional context
N/A

**Comment by DeD1rk** [comment]
I heard the same from some EVC members. Nice that you're able to reproduce, because it was working fine on my phone (with superuser permissions). Sounds like it's probably just a problem with the api's permissions. Would be nice to see what status code and corresponding message we get.

**Comment by DeD1rk** [comment]
Can reproduce through OpenAPI interface that this is a concrexit issue, I'll look into it soon.

**Comment by DeD1rk** [comment]
This appears to have been a misconfiguration of the committee permissions on the production concrexit.
