### ISSUE TITLE
Migrate to Flutter 3

### ISSUE THREAD

**Issue by LahaLuhem** [svthalia/Reaxit#225]
### Is your feature request related to a problem? Please describe.
- Basic initial app building fails, after upgrading to Flutter 3. The logs show that it because of some files using deprecated API.

### Describe the solution you'd like
Flutter 3 is out recently, and the basal codebase could benefit from migrating to the updated SDK. In the near coming future, these APIs will be put out of use anyways. The migration for my other apps has been easy, quick and seamless.

### Motivation
A lazy summary of the can be found [here](https://itnext.io/whats-new-in-flutter-3-0-in-brief-for-lazies-105dfe8bbf21).
+ Easier and more performant Firebase integration.
+ Newer and better Dart SDK.
+ Lots of really neat performance leaps.
+ Linux and MacOS are stable now
+ Easy to use and beautiful Material 3 design

### Describe alternatives you've considered
Downgrading the SDK.

### Additional context
[console.txt](https://github.com/svthalia/Reaxit/files/8772149/console.txt)
.

**Comment by DeD1rk** [comment]
Just waiting for https://github.com/LinusU/flutter_web_auth/pull/118 now. There's the option to use a git reference dependency temporarily but as it's not been merged yet, that's fragile, and there's no time pressure at all for this.
