### ISSUE TITLE
Push notifications are delayed or do not send at all

### ISSUE THREAD

**Issue by JorisBallemans** [svthalia/Reaxit#263]
### Describe the bug
When creating a push notification (scheduled or "direct") in the backend they do not arrive / send when expected (unclear if this is an app issue or concrexit). Sometimes users get a batch of notifications at the same time.

### How to reproduce
1. Go to the Thalia admin panel on concrexit
2. Create a push notification (either scheduled or "direct")

### Expected behavior
The app user should receive their message directly or on given scheduled time.

### Environment:
 - Device: Samsung Galaxy A52s 5g
 - OS: Android 12
 - Version: 3.2.0

### Additional context
It is unclear if this is a problem for the app or something with the server?

**Comment by DeD1rk** [comment]
This was a problem with cronjobs on the server. I thought it had been resolved a while ago, shortly after all of the beestfeest ticket url notifications and older stuff suddenly being sent. Is it still going wrong? Maybe @pingiun knows more about this?

**Comment by pingiun** [comment]
This is a problem with how our systemd timers run on the server. I'm not sure why they sometimes stop. We're still investigating this
