### ISSUE TITLE
Cancel orders that are paid with thalia pay

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/Reaxit#265]
### Is your feature request related to a problem? Please describe.

Canceling already paid food orders (with thalia pay) should be allowed. The api just accepts this

### Describe the solution you'd like
Fix the app

### Motivation
Same behavior as the site

### Additional context

**Comment by DeD1rk** [comment]
I just looked at the code, and it seems that it should allow cancelling/changing orders iff ((not paid) or paid with thalia pay), so only not when paid by cash or card

**Comment by JobDoesburg** [comment]
> I just looked at the code, and it seems that it should allow cancelling/changing orders iff ((not paid) or paid with thalia pay), so only not when paid by cash or card

Are you sure? Elina showed me this problem at the latest borrel.

But maybe it was because the deadline had already passed

**Comment by DeD1rk** [comment]
I mean I can try when I have time, but I'm pretty sure, and indeed if the time passed it's not possible, and it can fail if the api doesn't allow it for some reason (back when I made it deleting tpay payments was pretty much nondeterministic)

**Comment by JobDoesburg** [comment]
Meh I think its just the time then

**Comment by JAicewizard** [comment]
Maybe indicate that the deadline has passed in the app? Sounds like something that's useful to the user

**Comment by DeD1rk** [comment]
@JAicewizard i mean it already says 'It was possible to order until $end.' at the top of the screen
