### ISSUE TITLE
Add Sentry error reporting

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/Reaxit#30]
### Is your feature request related to a problem? Please describe.
It can happen that we need to know why the app is crashing for a lot of users.

### Describe the solution you'd like
We should implement error reporting to Sentry to make sure we are properly informed about the stability of the app.

### Motivation
I think I have already motivated this feature.

### Describe alternatives you've considered
There are no alternative services since we have a open source account for Sentry and concrexit already uses it as well.

**Comment by DeD1rk** [comment]
Is it enough if we report only uncaught exceptions? Or also anything unexpected from the api (stuff that makes an `ApiService` throw a caught `ApiException.unknownError`.

**Comment by se-bastiaan** [comment]
No it is specifically for uncaught exceptions
