### ISSUE TITLE
Fix the 'back' button while viewing a picture in an album

### ISSUE THREAD

**Issue by rvbrakel** [svthalia/Reaxit#326]
### Describe the bug
When viewing a picture, the 'back' button returns you to the album viewer instead of the album the picture is in itself. 

### How to reproduce
1. Go to Photos
2. Click on an album
3. Click on a picture
4. Press your back button
5. Cry that you have to re-open the album again.

### Expected behaviour
Just want to return to the album.

### Screenshots
Nahh

### Environment:

 - Device: [Galaxy S10]
 - OS: [Android v12]

**Comment by DeD1rk** [comment]
Duplicate of #325
