### ISSUE TITLE
Deregister from event when still in queue

### ISSUE THREAD

**Issue by tintin10q** [svthalia/Reaxit#343]
### What
You should be able to deregister from an event at any time if you are on the waiting list without paying the fine.

### Why
Currently, if you are in the waiting list you can not deregister after the deadline without paying a fine. This means that after the deadline when you are on the waiting list you can not really plan other things on this day because of the slim chance that you might get into the event. Because if you do get into the event, you would have to cancel the new plans you made and disappoint the new people or face the fine (which can be like 15 euros or more in some cases!). It also means that if you do plan other things that you can not give your spot to someone else on the waiting list. 

### Context
I think it makes sense that you would not be able to register again after deregistering after the deadline.

**Comment by JAicewizard** [comment]
Hey, thanks for the issue. I think that if you are on the waitinglist you should already be able to deregister without paying the fine. (I think that even when you went from the waiting list to the people actually registered you can still contact the organizers).
Can you post a screenshot of what it looks like for you right now and same on the website?

Ill look into whether or not you're supposed to receive a fine. If you are, there is nothing I can do, but if you're not supposed to but the app says you will I'll fix that.

**Comment by tintin10q** [comment]
The event has now passed so I can not check it out. But I remember that the popup with the fine still came up when I wanted to sign off when the deadline was passed even though I was on the waiting list.

**Comment by tintin10q** [comment]
@JAicewizard 

Ok here is an example 

![Screenshot_20230222_024108_ThaliApp.jpg](https://user-images.githubusercontent.com/24190849/220499232-dc1786cd-1930-440d-8741-e9f9bdd16d24.jpg)

![Screenshot_20230222_024104_ThaliApp.jpg](https://user-images.githubusercontent.com/24190849/220499241-00edcb57-a625-4c8d-b524-929557758c87.jpg)

**Comment by JAicewizard** [comment]
Thanks for the screenshots! I missed the popup before but that's included in the fix now. Hoping to release this evening. However you can safely deregister without a fine, you can also deregister via the website which shouldn't give a notification like this
