### ISSUE TITLE
Respect rotation of photos

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/Reaxit#366]
### Describe the bug
Photos in an album can have a rotation passed along. We don't use that right now, and we probably should.
### How to reproduce
Look at e.g. photo 37 in the 'thalia on ice' album (https://thalia.nu/members/photos/thalia-on-ice/).

### Expected behaviour
All photos are upright.

### Additional context
I'm not sure why the website passes a rotation, instead of just serving pictures that are upright.

**Comment by DeD1rk** [comment]
Might be best to fix it on concrexit instead, see https://github.com/svthalia/concrexit/issues/2852

**Comment by JAicewizard** [comment]
I was about to say, the website also uses the wrong rotation. Would indeed be nice to just rotate the image when uploading maybe?
