### ISSUE TITLE
Welcome page doesn't show external events

### ISSUE THREAD

**Issue by JasmijnB** [svthalia/Reaxit#385]
### Describe the bug
When opening the app in the welcome page, this does not show external events we put on the calendar. 

### How to reproduce
1. One of the first three events should be an external event
2. Go to the welcome page
3. Take a look at all the possible events
4. Compare this to the possible events in the calendar
5. See that external events are missing

### Expected behaviour
External events should be on the welcome page

**Comment by JAicewizard** [comment]
Did partners ask for this? I am not sure why this is this way, I will ask dirk (likely just because its easier), and otherwise this can probably be fixed the release after next release.
