### ISSUE TITLE
Some photos do not appear

### ISSUE THREAD

**Issue by ColonelPhantom** [svthalia/Reaxit#387]
### Describe the bug
Some committee photos are not displaying on the app

### How to reproduce
1. Go to Groups
2. Scroll down to Technicie
3. See that there is a placeholder image

### Expected behaviour
The committee photo should appear

### Environment:

 - Device: Mi 9T Pro
 - OS: Android 10
 - Version: Thaliapp V3.3.2
Also happened on other devices

### Additional context
The website does show the photos correctly, but it's probably related to the migration to S3.

**Comment by ColonelPhantom** [comment]
Seems like only "full" and "medium" work. I think I only wiped the thumbnails for medium, so I guess I'll need to wipe the others too. Sigh..

**Comment by JeeVee11** [comment]
Fixed in the website.
