### ISSUE TITLE
Implement themeable adaptive icons

### ISSUE THREAD

**Issue by stefanvi** [svthalia/Reaxit#406]
### What
The flutter app does not yet support Android 13's icon theming, which uses an additional monochromatic layer in the definition of the app icon. This allows the color of the icon to change to the theme color of the Android device.

### Why
Looks better. Now ThaliApp stands out:
![image](https://user-images.githubusercontent.com/60365750/231556266-5f831b80-106d-4801-9589-f9c2e9c7a47b.png)

### Context
Implementing this should be relatively easy, since our logo is not that complex.

**Comment by JAicewizard** [comment]
oh that looks very nice, would def be welcome
