### ISSUE TITLE
Typos in EventScreen

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/Reaxit#454]
### Describe the bug
There are two typos I know of:
1. '_our_ registration' in a snackbar after paying for event with Thalia Pay
2. A missing space after a period in the status text when registered but not yet paid.

### How to reproduce
1. Open event screen for an event where you're registered but haven't paid.
2. Observe typo 2.
3. Pay.
4. Observe typo 1 in the snackbar that pops up.

**Comment by JAicewizard** [comment]
I haven't found type 2 yet, all the status messages have a space after the period. But type 1 is fixed in #496
