### ISSUE TITLE
Some events don't show up in calendar

### ISSUE THREAD

**Issue by JeeVee11** [svthalia/Reaxit#465]
### Describe the bug
The GM on the 10th of October and the Master thesis market are on the calendar on the website, but don't show up on the app. 

### How to reproduce
1. Go to the calendar.
2. Scroll down to the 10th of October.
4. See that the GM is not there.

**Comment by JAicewizard** [comment]
I see that the GM is there, as is the master thesis market on tue 14th, could you restart the app and post a screenshot?

**Comment by JeeVee11** [comment]
> I see that the GM is there, as is the master thesis market on tue 14th, could you restart the app and post a screenshot?

Its working now :).
