### ISSUE TITLE
Possible to see memberlist when not a member

### ISSUE THREAD

**Issue by JeeVee11** [svthalia/Reaxit#470]
### Describe the bug
When somebody used to have access to the member list but not any more the list is still visible. On the website you get a 403 error.

### How to reproduce
1. Become a account that had a previous membership.
2. Click on memberlist.
3. See the updated memberlist.

### Expected behaviour
An error screen.

**Comment by DeD1rk** [comment]
This is actually a concrexit API issue. In the app it might be nice to show a banner if someone is not a member, but the normal NotAllowed error screens are fine too.
