### ISSUE TITLE
Add email addresses to committees

### ISSUE THREAD

**Issue by JACY24** [svthalia/Reaxit#471]
### What
Add the email addresses of committees to their pages on the app.

### Why
On the website, committees currently shows their email addresses so that members can send emails to committees if they have any questions. The website currently does not show these email addresses, and I think it would be nice to add the email addresses on the app as well to reflect the behaviour of the website.

**Comment by JAicewizard** [comment]
This sounds like a great idea, the next release will be another small bugfix, but we can likely include this in the one after that
