### ISSUE TITLE
App errors on certain event screen

### ISSUE THREAD

**Issue by JeeVee11** [svthalia/Reaxit#492]
### Describe the bug
When opening the  [alumni reunion cs and is](https://thalia.nu/events/alumni-reunion-cs-and-is-2023/) event, the screen shows for a bit but then says that an unknown error occurred.

### Environment:

 - Device: Pixel 6
 - OS: Android 14
 - Version 3.6.0

**Comment by DeD1rk** [comment]
This was an API issue, which is hotfixed. See https://github.com/svthalia/concrexit/pull/3563.
