### ISSUE TITLE
disable/grey out order food button

### ISSUE THREAD

**Issue by sijmenvb** [svthalia/Reaxit#505]
### What
disable/grey out order food button when you can no longer order food. (maybe even change the text)

### Why
it looks like you are still able to order food even though the deadline has passed. When I quickly check if I can still order, I don't actually push the button.

### Context
the app when ordering food for an event/borrel.

**Comment by JAicewizard** [comment]
We can't grey the button since you need it to view your order, but inside the order page it will update
