### ISSUE TITLE
Thabloid section uses outdated links leading to access denied errors

### ISSUE THREAD

**Issue by ColonelPhantom** [svthalia/Reaxit#517]
### Describe the bug
The Thabloid may give an "Access denied" error when trying to open a Thabloid.

### How to reproduce
1. (optional I think) Go to Thabloids
2. Leave app open for >1 hour
3. Tap a Thabloid

### Expected behaviour
The selected thabloid issue opens

### Screenshots
I just re-opened the app to test if that works around it, and it did, so I cannot. Ask again in an hour.

### Environment:

 - Device: Motorola Edge 50 Fusion
 - OS: Android 14
 - Version: v3.7.3

### Additional context
The API sends an "Expires" field, you should probably check if a URL is expired and if so retrieve a new one first.

**Comment by JAicewizard** [comment]
We have decided that the API is going to extend the expiration time, won't for this
