### ISSUE TITLE
Merchandise page

### ISSUE THREAD

**Issue by Luca-Castelnuovo** [svthalia/Reaxit#56]
### Is your feature request related to a problem? Please describe.
It is not possible to view merch in the app.

### Describe the solution you'd like
Show merch in app.

### Motivation
Merch is available on the site, so it would be nice to also have it available in the app.

**Comment by Luca-Castelnuovo** [comment]
@DeD1rk

**Comment by DeD1rk** [comment]
Blocked by concrexit issue #1645.

**Comment by DeD1rk** [comment]
Sounds like it's been decided not to do this anytime soon.
