### ISSUE TITLE
Pretty splash screens

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/Reaxit#64]
We currently have a simple image as a splashcreen with no transition to the first frame. We should at least make the image (esp. on android) nicer, and it would also be nice to fade to the first frame.

**Comment by se-bastiaan** [comment]
I would like to add that using splashscreens on android is not a best practice. If possible just load the app directly. It currently shows for 2ms and is stretched out.

**Comment by se-bastiaan** [comment]
![splash](https://user-images.githubusercontent.com/1799914/125605501-93562c9c-be7e-4362-a185-61f35f6a9a90.png)
