### ISSUE TITLE
Partner events are not included in the calendar

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/Reaxit#79]
### Describe the bug
Partner events are not included in the calendar.

### How to reproduce
1. Go to the calendar and look for the partner events that are currently active on staging.

### Expected behaviour
Should contain the partner events.

### Additional context
There is no v2 API for these events currently, so we need that to be implemented first: https://github.com/svthalia/concrexit/issues/1428.

**Comment by DeD1rk** [comment]
This is actually really very very tricky. In the old app, the calendar was not paginated, but now it is. I think the solution would be either:
- Not paginating the calendar
- Not paginating the partner events. Then store all partner events, and display only those before the last loaded normal event, unless all normal events have been loaded.
- Paginate both? Then we'd need to keep track of two cursors and things would become quite complicated.
- Combined concrexit endpoint (would be a good option if partner events are moved to the events app)

For now I think I'll implement the second option, as the number of partner events is usually much smaller than that of normal events.

**Comment by se-bastiaan** [comment]
I think the second solution is perfectly fine.

However, you could also think about it differently. Both endpoints should support a start and end query parameter, so you could technically use those after you determined the date of the first event. A bit like the calendar on the website. But I can understand that the concept is quite different from what we have in the app.
