### ISSUE TITLE
Style inconsistencies in the calendar view

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/Reaxit#80]
### Describe the bug
I've decided to make one issue for this instead of opening a couple:
- The months are centered instead of aligned to the left
- The days are centered instead of aligned to the left
- The colour of the days is black instead of grey
- Months are not sticky
- Colour of the time and location should have a 0.8 opacity
- When pressing a calendar item the press animation colour is not visible and it shows underneath the calendar item
- Calendar item border radius is 1 instead of 2

### How to reproduce
1. Go to the calendar view

### Expected behaviour
The description already contains this.

### Environment:
 - Device: OnePlus 8T (KB2003)
 - OS: Android 11
 - Local build

### Additional context
The old design (do note that it is a bit out of date) is available on Zeplin: https://zpl.io/2jZMN76

**Comment by DeD1rk** [comment]
Some context for the sticky headers:
When we first made the calendar screen here, there was no elegant option for sticky headers (only mediocre packages with Chinese documentation), but there is now an official flutter community package https://pub.dev/packages/sticky_headers.

**Comment by DeD1rk** [comment]
> The days are centered instead of aligned to the left

Since in English 3-character day notation is common (longer than the 2 characters in dutch) left aligning the day name looks a bit strange. I figured though that it would make more sense to right-align both the day number and weekday abbreviation, since they semantically correspond to the items to their right:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/41264528/126911847-30a29ed7-6e32-49c1-82e0-0dbfd88615b1.png">

I quite like it this way, what do you think?

**Comment by se-bastiaan** [comment]
I think it looks misaligned. The cards with the event info also have the text not centered.

**Comment by DeD1rk** [comment]
So you don't like right-aligned date/day labels? Now that you say it the cards do indeed look not-centered vertically. Ill fix that.

**Comment by se-bastiaan** [comment]
![Screenshot_20210728-215402.jpg](https://user-images.githubusercontent.com/1799914/127387093-769cf20d-d857-41fd-994e-ab6a806e5c85.jpg)

Inspiration was from Google calendar at the time because it works quite well for events too. So if we can replicate this or the iOS equivalent. Also nice :p

**Comment by DeD1rk** [comment]
That does have both the day name and the entire date/day label centered though... 

I think having it like that, with the day name on top is a nice idea. 

What about this:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/41264528/127393923-784cb35f-16d0-4104-a566-eb0b226d9adb.png">

**Comment by se-bastiaan** [comment]
![Screenshot_20210729-100323.jpg](https://user-images.githubusercontent.com/1799914/127455308-fbbecedb-64b3-49ef-bebb-09c64aba2df0.jpg)

**Comment by DeD1rk** [comment]
<img width="760" alt="image" src="https://user-images.githubusercontent.com/41264528/127479031-484f236d-2f8d-4003-9fec-ec47d67a99f7.png">

I think having the month in caps and a bit smaller looks somewhat better. In this one I actually increased the space above the day info. I think top-aligning that (i.e. overriding the fonts strut height) actually looks strange 🤔

**Comment by DeD1rk** [comment]
@se-bastiaan is the above acceptable?

**Comment by se-bastiaan** [comment]
> 
> 
> @se-bastiaan is the above acceptable?

LGTM Maybe it is different in dark mode or on device.

**Comment by DeD1rk** [comment]
Nice, Im quite happy with the dark version as well, but of course when all is done we should still take a good look at everything in dark mode.
